"""Unit tests for `app.release_verify`.

The fixtures here are real minisign output: a keypair generated by
the `minisign` CLI (v0.12) and a signature produced by the same CLI
in prehashed mode (`-S -H`). Using authentic fixtures rather than
synthesized-by-our-own-code vectors guards against a class of bug
where a self-test passes only because both sides are wrong in the
same way.

If you ever need to regenerate these:

    minisign -G -p test.pub -s test.key -W
    printf 'hello world for tideway tests' > sample.bin
    minisign -S -H -t 'tideway test fixture v1' \\
             -m sample.bin -s test.key -W

Then copy the relevant pieces below.
"""
from __future__ import annotations

import pytest

from app.release_verify import (
    SignatureError,
    TrustedKey,
    verify_artifact,
)


# Real minisign fixture — see module docstring for how to regenerate.
_SAMPLE_BYTES = b"hello world for tideway tests"

_GOOD_PUBKEY_B64 = "RWRv+hrD4n6IHnBYbNuii5cI+6kIjlObSklkq05gr6FAAv3jT9E2ZgzU"

# Full .minisig file as four lines (untrusted comment, sig blob,
# trusted comment, global sig blob) — verbatim from the minisign CLI.
_GOOD_SIG = """untrusted comment: signature from minisign secret key
RURv+hrD4n6IHihct4sqL4Rv4Eevp2LS1nvlxnKXi2hQf7Lu8jdSbQjBbFtXm1yBeMte4ea9kyxuC+yh413J14omlxLqfKpTfQg=
trusted comment: tideway test fixture v1
VORlSSWFJiAY+ATCrhb/7aIN38iGXCMAXqAgFe1L2iKiJcf1UQsp0H9iAoF3YBfOuupLYDVCm7L9mEq+GcKYAA==
"""


@pytest.fixture
def sample_artifact(tmp_path):
    """Write the fixture sample bytes to a tmp file and return its
    path. The signature in `_GOOD_SIG` was generated against exactly
    these bytes, so writing them to a file gives a verify-able
    artifact for the happy-path test."""
    p = tmp_path / "sample.bin"
    p.write_bytes(_SAMPLE_BYTES)
    return p


@pytest.fixture
def trusted_key():
    return TrustedKey(pubkey_b64=_GOOD_PUBKEY_B64, label="test-primary")


# --- happy path ---------------------------------------------------------


def test_verify_good_signature_returns_matching_key(sample_artifact, trusted_key):
    used = verify_artifact(sample_artifact, _GOOD_SIG, [trusted_key])
    assert used.label == "test-primary"


def test_verify_walks_multiple_trusted_keys(sample_artifact, trusted_key):
    """A real release-time setup will have several trusted keys
    (primary + cold backup). The verifier should walk the list and
    pick the right one even when the signing key isn't first."""
    decoy = TrustedKey(
        pubkey_b64="RWQAAAAAAAAAAHBYbNuii5cI+6kIjlObSklkq05gr6FAAv3jT9E2ZgzU",
        label="decoy-not-the-signer",
    )
    used = verify_artifact(sample_artifact, _GOOD_SIG, [decoy, trusted_key])
    assert used.label == "test-primary"


# --- failure modes ------------------------------------------------------


def test_verify_rejects_tampered_artifact(tmp_path, trusted_key):
    """A single appended byte is enough to invalidate the BLAKE2b
    prehash. We're checking that the verifier actually does the file
    hash, rather than verifying only the global signature."""
    tampered = tmp_path / "tampered.bin"
    tampered.write_bytes(_SAMPLE_BYTES + b"!")
    with pytest.raises(SignatureError, match="file signature"):
        verify_artifact(tampered, _GOOD_SIG, [trusted_key])


def test_verify_rejects_unknown_key(sample_artifact):
    """If the .minisig was made by a key the build doesn't trust,
    we should reject before doing the curve math, with an error
    that names the encountered and known key ids so a misconfig is
    debuggable."""
    other = TrustedKey(
        pubkey_b64="RWQAAAAAAAAAAHBYbNuii5cI+6kIjlObSklkq05gr6FAAv3jT9E2ZgzU",
        label="other",
    )
    with pytest.raises(SignatureError, match="isn't in this build's trusted set"):
        verify_artifact(sample_artifact, _GOOD_SIG, [other])


def test_unknown_key_error_uses_minisign_display_order(sample_artifact):
    """Minisign prints key ids big-endian in pubkey comment lines
    (`minisign public key XXXXXXXX`) but stores them little-endian
    in the binary blob. Our error messages need to match the
    display convention, otherwise a user looking at the .pub file
    on disk and the error toast on screen sees two different ids
    and can't tell whether they actually correspond.

    For the test fixture, the pub file's comment line says
    `1E887EE2C31AFA6F`. The verifier's error must use that same
    rendering."""
    other = TrustedKey(
        pubkey_b64="RWQAAAAAAAAAAHBYbNuii5cI+6kIjlObSklkq05gr6FAAv3jT9E2ZgzU",
        label="other",
    )
    with pytest.raises(SignatureError) as excinfo:
        verify_artifact(sample_artifact, _GOOD_SIG, [other])
    # The fixture's pubkey is `1E887EE2C31AFA6F` per the original
    # `untrusted comment: minisign public key 1E887EE2C31AFA6F` line
    # in test.pub.
    assert "1E887EE2C31AFA6F" in str(excinfo.value)


def test_verify_refuses_empty_trusted_set(sample_artifact):
    """The 'no keys configured' state needs a distinctive error so a
    bad release_keys.py shows up clearly during a release dry-run,
    rather than looking like a generic verify failure."""
    with pytest.raises(SignatureError, match="No trusted release-signing keys"):
        verify_artifact(sample_artifact, _GOOD_SIG, [])


def test_verify_rejects_tampered_trusted_comment(sample_artifact, trusted_key):
    """The trusted comment is the part we'd surface in a UI ('verified
    release X by key Y'). It's bound to the file by the global
    signature; mutating it should fail the global-sig check while
    the file signature itself remains valid."""
    bad_sig = _GOOD_SIG.replace(
        "trusted comment: tideway test fixture v1",
        "trusted comment: an attacker rewrote this line",
    )
    with pytest.raises(SignatureError, match="trusted-comment signature"):
        verify_artifact(sample_artifact, bad_sig, [trusted_key])


def test_verify_rejects_legacy_raw_ed25519_marker(sample_artifact, trusted_key):
    """Tideway only signs in prehashed mode (`minisign -S -H`,
    algorithm marker 'ED' = 0x45 0x44). A signature in the legacy
    raw-message mode (marker 'Ed' = 0x45 0x64) must be rejected even
    if the underlying Ed25519 verification would technically pass —
    we don't want a downgrade path to silently exist."""
    # 0x45 0x44 -> base64 starts with "RUR..."; 0x45 0x64 (legacy)
    # base64-encodes with "RWQ..." as the leading three chars.
    legacy_sig = _GOOD_SIG.replace("RURv", "RWRv", 1)
    with pytest.raises(SignatureError, match="prehashed"):
        verify_artifact(sample_artifact, legacy_sig, [trusted_key])


def test_verify_rejects_truncated_signature_file(sample_artifact, trusted_key):
    """A .minisig file with fewer than 4 non-empty lines is structurally
    invalid — fail with a parse-level error rather than dragging the
    bytes through Ed25519."""
    truncated = "\n".join(_GOOD_SIG.splitlines()[:2]) + "\n"
    with pytest.raises(SignatureError, match="non-empty lines"):
        verify_artifact(sample_artifact, truncated, [trusted_key])


def test_verify_rejects_non_base64_payload(sample_artifact, trusted_key):
    """If the second line isn't valid base64 we should bail at parse
    time with a clear message, not blow up inside b64decode."""
    garbled = _GOOD_SIG.replace(
        "RURv+hrD4n6IHihct4sqL4Rv4Eevp2LS1nvlxnKXi2hQf7Lu8jdSbQjBbFtXm1yBeMte4ea9kyxuC+yh413J14omlxLqfKpTfQg=",
        "this is not base64 at all $$$",
    )
    with pytest.raises(SignatureError, match="base64"):
        verify_artifact(sample_artifact, garbled, [trusted_key])


def test_verify_rejects_pubkey_with_wrong_length(sample_artifact):
    """A typo in the trusted-keys list (e.g. truncated paste) should
    surface as a clear configuration error, not a generic verify
    failure."""
    short = TrustedKey(pubkey_b64="RWQAAA==", label="too-short")
    with pytest.raises(SignatureError, match="wrong length"):
        verify_artifact(sample_artifact, _GOOD_SIG, [short])
