import { useEffect, useRef, useState } from "react";
import { useLocation, useParams } from "react-router-dom";
import { Radio as RadioIcon } from "lucide-react";
import { api } from "@/api/client";
import type { OnDownload } from "@/api/download";
import type { Track } from "@/api/types";
import { useApi } from "@/hooks/useApi";
import { usePlayerActions, usePlayerMeta } from "@/hooks/PlayerContext";
import { AddTracksToPlaylistButton } from "@/components/AddTracksToPlaylistButton";
import { CollectionOverflowMenu } from "@/components/CollectionOverflowMenu";
import { DetailHero } from "@/components/DetailHero";
import { PlayAllButton } from "@/components/PlayAllButton";
import { ShuffleButton } from "@/components/ShuffleButton";
import { TrackList } from "@/components/TrackList";
import { ErrorView } from "@/components/ErrorView";
import { HeroSkeleton, TrackListSkeleton } from "@/components/Skeletons";

type RadioSeed = { name: string; cover: string | null } | null;

interface Props {
  kind: "artist" | "track";
  onDownload: OnDownload;
}

/**
 * Dedicated radio page (artist or track). Mirrors how Tidal / Spotify /
 * Apple Music handle "start radio" — a dedicated surface that plays
 * immediately, with the seed's metadata in the hero and the full
 * generated queue as a track list. Feels more discoverable than
 * silently queuing a bunch of tracks in the now-playing bar.
 *
 * Seed metadata (name + cover):
 *   - Artist radio: fetched from /api/artist/:id (we need it anyway
 *     for the hero, and the endpoint is fast).
 *   - Track radio: passed via router state from wherever the user
 *     clicked "Go to track radio" — no /api/track/:id exists, and
 *     adding one just for the hero is overkill. Direct-URL reloads
 *     fall back to a generic "Track Radio" header.
 */
export function RadioPage({ kind, onDownload }: Props) {
  const { id = "" } = useParams();
  const location = useLocation();
  const [shuffleIntent, setShuffleIntent] = useState(false);
  // Router state carries the seed for track radio since we have no
  // cheap metadata endpoint for tracks. Artist radio also respects
  // state as a short-circuit to skip the extra fetch.
  const stateSeed = (location.state as { seed?: RadioSeed } | null)?.seed
    ?? null;

  const radio = useApi(() => fetchRadio(kind, id), [kind, id]);

  // For artist radio we can also fetch the artist payload to get a
  // picture + canonical name. Cheap and runs in parallel with the
  // radio fetch.
  const artistMeta = useApi(
    () =>
      kind === "artist"
        ? api.artist(id).catch(() => null)
        : Promise.resolve(null),
    [kind, id],
  );

  const tracks = radio.data ?? [];
  const seed: RadioSeed = stateSeed
    ?? (kind === "artist" && artistMeta.data
      ? { name: artistMeta.data.name, cover: artistMeta.data.picture }
      : tracks[0]
        ? {
            name: tracks[0].name,
            cover: tracks[0].album?.cover ?? null,
          }
        : null);

  const eyebrow = kind === "artist" ? "Artist Radio" : "Track Radio";
  const title = seed?.name
    ?? (kind === "artist" ? "Artist Radio" : "Track Radio");

  // Kick off playback once, as soon as tracks arrive. Keyed on
  // id+kind so navigating to a different radio page restarts the
  // autoplay guard.
  const playedRef = useRef<string | null>(null);
  const actions = usePlayerActions();
  const { track: currentTrack } = usePlayerMeta();
  useEffect(() => {
    if (!tracks.length) return;
    const k = `${kind}:${id}`;
    if (playedRef.current === k) return;
    playedRef.current = k;
    // Don't stomp the user's playback if they somehow landed on this
    // page while the seed is already playing (e.g. back-navigation
    // after the radio already started).
    if (currentTrack && currentTrack.id === tracks[0].id) return;
    actions.play(tracks[0], tracks);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [tracks.length, id, kind]);

  if (radio.loading && tracks.length === 0) {
    return (
      <div>
        <HeroSkeleton />
        <div className="mt-10">
          <TrackListSkeleton />
        </div>
      </div>
    );
  }
  if (radio.error) return <ErrorView error={radio.error} />;

  return (
    <div>
      <DetailHero
        eyebrow={eyebrow}
        title={title}
        cover={seed?.cover ?? null}
        round={kind === "artist"}
        meta={
          <div className="flex items-center gap-2 text-sm">
            <RadioIcon className="h-4 w-4" />
            <span>{tracks.length} tracks · generated by Tidal</span>
          </div>
        }
        actions={
          tracks.length > 0 ? (
            <>
              <PlayAllButton
                tracks={tracks}
                // Radio doesn't have a first-class Tidal id — seed it
                // with the ARTIST or TRACK the radio spun up from so
                // plays still attribute to something meaningful on
                // Recently Played.
                source={{
                  type: kind === "artist" ? "ARTIST" : "TRACK",
                  id,
                }}
                shuffleIntent={shuffleIntent}
              />
              <ShuffleButton value={shuffleIntent} onChange={setShuffleIntent} />
              <div className="ml-auto flex items-center gap-6">
                <AddTracksToPlaylistButton tracks={tracks} />
                <CollectionOverflowMenu tracks={tracks} />
              </div>
            </>
          ) : null
        }
      />
      <div className="mt-8">
        <TrackList
          tracks={tracks}
          onDownload={onDownload}
          showAlbum
          source={{ type: kind === "artist" ? "ARTIST" : "TRACK", id }}
        />
      </div>
    </div>
  );
}

async function fetchRadio(kind: "artist" | "track", id: string): Promise<Track[]> {
  if (kind === "artist") return api.artistRadio(id);
  return api.trackRadio(id);
}
